Repository Dwlad90/stylex-swc-plugin, pull requests merged in 2025-01, with the labels that each got.

#174 ci(ga): fire cleanup on closing PR
  .github/workflows/cleanup.yaml
  .github/workflows/npm.yml
Labels: CI

#178 ci(workflows): add cleanup workflow
  .github/workflows/cleanup-branch.yaml
  .github/workflows/cleanup-pr.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/npm.yml
Labels: CI

#180 ci(release): check fast-forward only against master
  .github/workflows/release.yml
Labels: CI

#182 ci(release): add retries to checking NPM workflow status
  .github/workflows/npm.yml
  .github/workflows/release.yml
Labels: CI

#188 ci(ga): clean caches after PR merged
  .github/workflows/cleanup-branch.yaml
  .github/workflows/cleanup-pr.yaml
  .github/workflows/fast-forward.yml
  .github/workflows/npm.yml
  .github/workflows/pr-validation.yml
  .github/workflows/release.yml
Labels: CI

#191 fix(@stylexwc/nextjs-plugin): only log webpack details in debug mode
  packages/nextjs-plugin/src/index.ts
Labels: fix

#194 chore(get_package_json): generate more detailed error when package.json parsing failed
  crates/stylex-path-resolver/src/package_json/mod.rs
Labels: chore

#198 chore(deps): upgrade @stylexjs/stylex to 0.10.0
  apps/esbuild-unplugin-example/package.json
  apps/farm-unplugin-example/package.json
  apps/nextjs-example/package.json
  apps/nextjs-postcss-example/package.json
  apps/nextjs-swc-example/package.json
  apps/rollup-example/package.json
  apps/rollup-unplugin-example/package.json
  apps/rsbuild-unplugin-example/package.json
  apps/rspack-unplugin-example/package.json
  apps/solid-unplugin-example/package.json
  apps/vite-unplugin-example/package.json
  apps/vue-unplugin-example/package.json
  apps/webpack-example/package.json
  apps/webpack-unplugin-example/package.json
  crates/stylex-path-resolver/fixtures/workspace/package.json
  crates/stylex-rs-compiler/package.json
  packages/nextjs-swc-plugin/package.json
  packages/postcss-plugin/package.json
  packages/rollup-plugin/package.json
  packages/unplugin/package.json
  packages/webpack-plugin/package.json
  pnpm-lock.yaml
Labels: chore, dependencies

#199 ci(npm): copy @stylexswc/rs-compiler artifacts
  .github/workflows/npm.yml
  .github/workflows/pr-validation.yml
Labels: CI

#202 fix(packagejsonextended): turn name field to optional
  crates/stylex-path-resolver/src/package_json/mod.rs
  crates/stylex-path-resolver/src/resolvers/mod.rs
  crates/stylex-shared/src/shared/structures/state_manager.rs
  crates/stylex-shared/src/shared/structures/tests/fixtures/package_json_with_name/package.json
  crates/stylex-shared/src/shared/structures/tests/fixtures/package_json_without_name/package.json
  crates/stylex-shared/src/shared/structures/tests/get_canonical_file_path_test.rs
  crates/stylex-shared/src/shared/structures/tests/get_package_name_and_path_test.rs
  crates/stylex-shared/src/shared/structures/tests/mod.rs
Labels: fix, bug

#207 chore: add `postbuild` script to all buildable public packages
  .github/PULL_REQUEST_TEMPLATE.md
  crates/stylex-path-resolver/package.json
  crates/stylex-rs-compiler/package.json
  crates/stylex-swc-plugin/package.json
  crates/stylex-test-parser/package.json
  packages/jest/package.json
  packages/nextjs-plugin/package.json
  packages/nextjs-swc-plugin/package.json
  packages/postcss-plugin/package.json
  packages/rollup-plugin/package.json
  packages/unplugin/package.json
  packages/webpack-plugin/package.json
  scripts/packages/build/rust.sh
Labels: chore

#208 fix: initial build pipeline
  apps/nextjs-postcss-example/package.json
  apps/nextjs-swc-example/package.json
  apps/rollup-unplugin-example/package.json
  apps/rollup-unplugin-example/rollup.config.mjs
  apps/solid-unplugin-example/package.json
  package.json
  pnpm-lock.yaml
Labels: fix, bug

#209 chore: remove @stylexswc/swc-plugin
  Cargo.lock
  README.md
  apps/nextjs-swc-example/.eslintrc.js
  apps/nextjs-swc-example/.gitignore
  apps/nextjs-swc-example/README.md
  apps/nextjs-swc-example/app/CardTokens.stylex.ts
  apps/nextjs-swc-example/app/Counter.tsx
  apps/nextjs-swc-example/app/favicon.ico
  apps/nextjs-swc-example/app/globalTokens.stylex.ts
  apps/nextjs-swc-example/app/layout.tsx
  apps/nextjs-swc-example/app/page.tsx
  apps/nextjs-swc-example/components/Card.tsx
  apps/nextjs-swc-example/next.config.js
  apps/nextjs-swc-example/package.json
  apps/nextjs-swc-example/public/next.svg
  apps/nextjs-swc-example/public/vercel.svg
  apps/nextjs-swc-example/tsconfig.json
  apps/nextjs-swc-example/typetests/test1.tsx
  apps/nextjs-swc-example/typetests/test2.tsx
  apps/nextjs-swc-example/typetests/test3.tsx
  apps/nextjs-swc-example/typetests/test4.tsx
  apps/nextjs-swc-example/typetests/theming/ButtonTokenThemes.ts
  apps/nextjs-swc-example/typetests/theming/ButtonTokens.stylex.ts
  apps/nextjs-swc-example/typetests/theming1.tsx
  apps/nextjs-swc-example/typetests/typetests.ts
  crates/stylex-swc-plugin/.editorconfig
  crates/stylex-swc-plugin/.eslintignore
  crates/stylex-swc-plugin/.gitignore
  crates/stylex-swc-plugin/.lintstagedrc.js
  crates/stylex-swc-plugin/.prettierignore
  crates/stylex-swc-plugin/Cargo.toml
  crates/stylex-swc-plugin/LICENSE
  crates/stylex-swc-plugin/README.md
  crates/stylex-swc-plugin/package.json
  crates/stylex-swc-plugin/src/lib.rs
  packages/nextjs-swc-plugin/.lintstagedrc.js
  packages/nextjs-swc-plugin/README.md
  packages/nextjs-swc-plugin/package.json
  packages/nextjs-swc-plugin/src/index.ts
  packages/nextjs-swc-plugin/tsconfig.build.json
  packages/nextjs-swc-plugin/tsconfig.json
  packages/nextjs-swc-plugin/tsconfig.typecheck.json
  packages/nextjs-swc-plugin/typings/browserslist/index.d.ts
  pnpm-lock.yaml
  turbo.json
Labels: chore

#213 feat(stylex_compiler_rs): add `normalize_rs_options` util
  crates/stylex-rs-compiler/src/lib.rs
  crates/stylex-rs-compiler/src/structs/mod.rs
  crates/stylex-shared/src/shared/structures/state_manager.rs
  crates/stylex-shared/src/shared/structures/stylex_options.rs
  crates/stylex-shared/src/shared/structures/stylex_state_options.rs
  crates/stylex-shared/src/shared/structures/tests/get_canonical_file_path_test.rs
  packages/jest/src/index.ts
  packages/postcss-plugin/src/bundler.ts
  packages/postcss-plugin/src/index.ts
  packages/rollup-plugin/src/index.ts
  packages/unplugin/src/index.ts
  packages/unplugin/src/utils/normalizeOptions.ts
  packages/webpack-plugin/src/utils.ts
Labels: feature

#214 fix: disable checking artifacts because of bun on Windows
  crates/stylex-rs-compiler/package.json
Labels: fix, bug

#216 fix(stylex_compiler_rs): resolving StyleX calls from dependencies
  crates/stylex-path-resolver/src/resolvers/mod.rs
  crates/stylex-path-resolver/src/resolvers/tests.rs
Labels: fix, bug

#217 fix(stylex_compiler_rs): improve resolving StyleX calls from dependencies
  crates/stylex-path-resolver/src/resolvers/mod.rs
  crates/stylex-path-resolver/src/resolvers/tests.rs
Labels: fix, bug

#218 ci(ga): fix excluding turbo cache
  .github/workflows/cleanup-branch.yaml
  .github/workflows/cleanup-pr.yaml
  .github/workflows/cleanup.yaml
  .github/workflows/fast-forward.yml
  .github/workflows/npm.yml
Labels: CI

#220 chore(deps): move @stylexswc/rs-compiler to dependencies
  .github/release.yml
  .github/workflows/conventional-label.yaml
  packages/jest/package.json
  packages/nextjs-plugin/package.json
  packages/postcss-plugin/package.json
  packages/rollup-plugin/package.json
  packages/webpack-plugin/package.json
  pnpm-lock.yaml
Labels: dependencies

#221 chore: patch `script` package to use `cross-spawn`
  .github/workflows/release.yml
  crates/stylex-rs-compiler/package.json
  package.json
  patches/scripty@2.1.1.patch
  pnpm-lock.yaml
Labels: chore

#224 fix(stylex_path_resolver): export field resolution with multiple node_modules in a workspace
  crates/stylex-path-resolver/fixtures/exports/node_modules/stylex-lib-dist-main/node_modules/.gitkeep
  crates/stylex-path-resolver/src/file_system/mod.rs
  crates/stylex-path-resolver/src/package_json/mod.rs
  crates/stylex-path-resolver/src/resolvers/mod.rs
  crates/stylex-path-resolver/src/resolvers/tests.rs
  crates/stylex-rs-compiler/package.json
  crates/stylex-shared/package.json
  crates/stylex-shared/src/shared/structures/state_manager.rs
  pnpm-lock.yaml
Labels: fix, bug
